// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WellnessAPI.Data;

#nullable disable

namespace WellnessAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260527203115_Phase3Schema")]
    partial class Phase3Schema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.Anetaresim", b =>
                {
                    b.Property<int>("AnetaresimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AnetaresimId"));

                    b.Property<decimal>("CmimiPaguar")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("DataFillimit")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataMbarimit")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("KlientId")
                        .HasColumnType("int");

                    b.Property<int>("PaketId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentProvider")
                        .HasColumnType("longtext");

                    b.Property<string>("PaymentReference")
                        .HasColumnType("longtext");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasDefaultValue("Manual")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Statusi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StripeSessionId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("AnetaresimId");

                    b.HasIndex("KlientId");

                    b.HasIndex("PaketId");

                    b.HasIndex("StripeSessionId");

                    b.ToTable("Anetaresimet");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EntityId")
                        .HasColumnType("longtext");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("NewValues")
                        .HasColumnType("longtext");

                    b.Property<string>("OldValues")
                        .HasColumnType("longtext");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.ConsentLog", b =>
                {
                    b.Property<int>("ConsentLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ConsentLogId"));

                    b.Property<bool>("Accepted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ConsentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<int?>("KlientId")
                        .HasColumnType("int");

                    b.Property<string>("UserAgent")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ConsentLogId");

                    b.HasIndex("KlientId", "ConsentType", "Version");

                    b.HasIndex("UserId", "ConsentType", "Version");

                    b.ToTable("ConsentLogs");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.Furnizuesi", b =>
                {
                    b.Property<int>("FurnizuesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FurnizuesId"));

                    b.Property<string>("Adresa")
                        .HasColumnType("longtext");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataRegjistrimit")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Emri")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("KontaktPersona")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefoni")
                        .HasColumnType("longtext");

                    b.HasKey("FurnizuesId");

                    b.HasIndex("Emri");

                    b.ToTable("Furnizuesit");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.Klient", b =>
                {
                    b.Property<int>("KlientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("KlientId"));

                    b.Property<DateTime?>("DataLindjes")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataRegjistrimit")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Emri")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FotoPath")
                        .HasColumnType("longtext");

                    b.Property<string>("Gjinia")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("KushtetShendetesore")
                        .HasColumnType("longtext");

                    b.Property<string>("LoyaltyTier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasDefaultValue("Bronze")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Mbiemri")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefoni")
                        .HasColumnType("longtext");

                    b.HasKey("KlientId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Klientet");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.KlientMatje", b =>
                {
                    b.Property<int>("MatjeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MatjeId"));

                    b.Property<decimal?>("BeliCm")
                        .HasColumnType("decimal(6,2)");

                    b.Property<DateTime>("DataMatjes")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("GjatesiaCm")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("KlientId")
                        .HasColumnType("int");

                    b.Property<decimal?>("KofshaCm")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("PeshaKg")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Shenim")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("YndyraTrupore")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("MatjeId");

                    b.HasIndex("KlientId", "DataMatjes");

                    b.ToTable("KlientMatjet");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.KlientPika", b =>
                {
                    b.Property<int>("PikaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PikaId"));

                    b.Property<DateTime>("DataKrijimit")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("KlientId")
                        .HasColumnType("int");

                    b.Property<int?>("LidhjeId")
                        .HasColumnType("int");

                    b.Property<int>("Pike")
                        .HasColumnType("int");

                    b.Property<string>("Shenim")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("PikaId");

                    b.HasIndex("DataKrijimit");

                    b.HasIndex("KlientId");

                    b.ToTable("KlientPikat");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.KlientProgram", b =>
                {
                    b.Property<int>("KpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("KpId"));

                    b.Property<DateTime>("DataFillimit")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataMbarimit")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("KlientId")
                        .HasColumnType("int");

                    b.Property<int>("ProgramId")
                        .HasColumnType("int");

                    b.Property<int>("Progresi")
                        .HasColumnType("int");

                    b.Property<string>("Statusi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("KpId");

                    b.HasIndex("KlientId");

                    b.HasIndex("ProgramId");

                    b.ToTable("KlientProgramet");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.KlientShenim", b =>
                {
                    b.Property<int>("ShenimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ShenimId"));

                    b.Property<DateTime>("DataKrijimit")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("KlientId")
                        .HasColumnType("int");

                    b.Property<string>("Permbajtja")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Privat")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("TerapistId")
                        .HasColumnType("int");

                    b.Property<int?>("TerminId")
                        .HasColumnType("int");

                    b.Property<string>("Tipi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ShenimId");

                    b.HasIndex("DataKrijimit");

                    b.HasIndex("KlientId");

                    b.HasIndex("TerminId");

                    b.ToTable("KlientShenime");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.Lajmerimi", b =>
                {
                    b.Property<int>("LajmerimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LajmerimId"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Audienca")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataKrijimit")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataSkadimit")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Permbajtja")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Prioriteti")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titulli")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("LajmerimId");

                    b.HasIndex("DataKrijimit");

                    b.ToTable("Lajmerimet");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.Lokacioni", b =>
                {
                    b.Property<int>("LokacioniId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LokacioniId"));

                    b.Property<string>("Adresa")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Emri")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Telefoni")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("LokacioniId");

                    b.HasIndex("Emri")
                        .IsUnique();

                    b.ToTable("Lokacionet");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Link")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId", "IsRead", "CreatedAt");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.PaketaWellness", b =>
                {
                    b.Property<int>("PaketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PaketId"));

                    b.Property<bool>("Aktive")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Cmimi")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("EmriPaketes")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("KohezgjatjaMuaj")
                        .HasColumnType("int");

                    b.Property<string>("Pershkrimi")
                        .HasColumnType("longtext");

                    b.Property<string>("SherbimiPerfshire")
                        .HasColumnType("longtext");

                    b.HasKey("PaketId");

                    b.ToTable("PaketaWellness");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.Produkt", b =>
                {
                    b.Property<int>("ProduktId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProduktId"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Cmimi")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("EmriProduktit")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Kategoria")
                        .HasColumnType("longtext");

                    b.Property<string>("Pershkrimi")
                        .HasColumnType("longtext");

                    b.Property<int>("SasiaStok")
                        .HasColumnType("int");

                    b.HasKey("ProduktId");

                    b.ToTable("Produktet");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.Program", b =>
                {
                    b.Property<int>("ProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProgramId"));

                    b.Property<string>("Dieta")
                        .HasColumnType("longtext");

                    b.Property<string>("EmriProgramit")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("KohezgjatjaJave")
                        .HasColumnType("int");

                    b.Property<string>("Pershkrimi")
                        .HasColumnType("longtext");

                    b.Property<string>("Qellimi")
                        .HasColumnType("longtext");

                    b.Property<string>("Ushtrimet")
                        .HasColumnType("longtext");

                    b.HasKey("ProgramId");

                    b.ToTable("Programet");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.Pushimi", b =>
                {
                    b.Property<int>("PushimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PushimId"));

                    b.Property<string>("Arsyeja")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataFillimit")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataKerkimit")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataMbarimit")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Statusi")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TerapistId")
                        .HasColumnType("int");

                    b.HasKey("PushimId");

                    b.HasIndex("Statusi");

                    b.HasIndex("TerapistId");

                    b.ToTable("Pushimet");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.Salla", b =>
                {
                    b.Property<int>("SallaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SallaId"));

                    b.Property<bool>("Aktive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Emri")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("Kapaciteti")
                        .HasColumnType("int");

                    b.Property<string>("Pershkrimi")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipi")
                        .HasColumnType("longtext");

                    b.HasKey("SallaId");

                    b.HasIndex("Emri")
                        .IsUnique();

                    b.ToTable("Sallat");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.Sherbim", b =>
                {
                    b.Property<int>("SherbimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SherbimId"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Cmimi")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("EmriSherbimit")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Kategoria")
                        .HasColumnType("longtext");

                    b.Property<int>("KohezgjatjaMin")
                        .HasColumnType("int");

                    b.Property<string>("Pershkrimi")
                        .HasColumnType("longtext");

                    b.HasKey("SherbimId");

                    b.ToTable("Sherbimet");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.ShitjeProdukteve", b =>
                {
                    b.Property<int>("ShitjeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ShitjeId"));

                    b.Property<decimal>("CmimiTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("DataShitjes")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("KlientId")
                        .HasColumnType("int");

                    b.Property<int>("ProduktId")
                        .HasColumnType("int");

                    b.Property<int>("Sasia")
                        .HasColumnType("int");

                    b.Property<string>("StatusiPageses")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipiPageses")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ShitjeId");

                    b.HasIndex("KlientId");

                    b.HasIndex("ProduktId");

                    b.ToTable("ShitjetProduktet");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.Template", b =>
                {
                    b.Property<int>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TemplateId"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("Subject")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("longtext");

                    b.HasKey("TemplateId");

                    b.HasIndex("Key", "Channel")
                        .IsUnique();

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.Terapist", b =>
                {
                    b.Property<int>("TerapistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TerapistId"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Emri")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Licenca")
                        .HasColumnType("longtext");

                    b.Property<int?>("LokacioniId")
                        .HasColumnType("int");

                    b.Property<string>("Mbiemri")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Specializimi")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefoni")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.HasKey("TerapistId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("LokacioniId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Terapistet");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.Termin", b =>
                {
                    b.Property<int>("TerminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TerminId"));

                    b.Property<DateTime>("DataTerminit")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("KlientId")
                        .HasColumnType("int");

                    b.Property<int?>("LokacioniId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("OraFillimit")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("OraMbarimit")
                        .HasColumnType("time(6)");

                    b.Property<DateTime?>("ProposedEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ProposedStart")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ReminderEmailSentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ReminderSmsSentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RescheduleNote")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RescheduleProposedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RescheduleProposedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("Shenimet")
                        .HasColumnType("longtext");

                    b.Property<int>("SherbimId")
                        .HasColumnType("int");

                    b.Property<string>("Statusi")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<int>("TerapistId")
                        .HasColumnType("int");

                    b.HasKey("TerminId");

                    b.HasIndex("KlientId");

                    b.HasIndex("LokacioniId");

                    b.HasIndex("SherbimId");

                    b.HasIndex("TerapistId");

                    b.ToTable("Terminet");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.Vleresim", b =>
                {
                    b.Property<int>("VleresimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("VleresimId"));

                    b.Property<DateTime>("DataVleresimit")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("KlientId")
                        .HasColumnType("int");

                    b.Property<string>("Komenti")
                        .HasColumnType("longtext");

                    b.Property<int>("Nota")
                        .HasColumnType("int");

                    b.Property<int>("SherbimId")
                        .HasColumnType("int");

                    b.Property<int>("TerapistId")
                        .HasColumnType("int");

                    b.HasKey("VleresimId");

                    b.HasIndex("SherbimId");

                    b.HasIndex("TerapistId");

                    b.HasIndex("KlientId", "SherbimId")
                        .IsUnique();

                    b.ToTable("Vlereisimet");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.Zbritja", b =>
                {
                    b.Property<int>("ZbritjeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ZbritjeId"));

                    b.Property<bool>("Aktive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataFillimit")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataMbarimit")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("HereshShfrytezuar")
                        .HasColumnType("int");

                    b.Property<string>("Kodi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("LimitiPerdorimit")
                        .HasColumnType("int");

                    b.Property<decimal>("PerqindjaZbritjes")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("ZbritjeId");

                    b.HasIndex("Kodi")
                        .IsUnique();

                    b.ToTable("Zbritjet");
                });

            modelBuilder.Entity("WellnessAPI.Models.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Adresa")
                        .HasColumnType("longtext");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("GdprErasureRequested")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("GdprErasureRequestedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("KlientId")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("PrivacyPolicyAccepted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("PrivacyPolicyAcceptedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("SmsOptIn")
                        .HasDefaultValue(true)
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TerapistId")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("TotpEnabledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TotpSecret")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("WellnessAPI.Models.Identity.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "UsedAt", "ExpiresAt");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("WellnessAPI.Models.Identity.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WellnessAPI.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WellnessAPI.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WellnessAPI.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WellnessAPI.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.Anetaresim", b =>
                {
                    b.HasOne("WellnessAPI.Models.Domain.Klient", "Klienti")
                        .WithMany("Anetaresimet")
                        .HasForeignKey("KlientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WellnessAPI.Models.Domain.PaketaWellness", "Paketa")
                        .WithMany("Anetaresimet")
                        .HasForeignKey("PaketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Klienti");

                    b.Navigation("Paketa");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.ConsentLog", b =>
                {
                    b.HasOne("WellnessAPI.Models.Domain.Klient", "Klienti")
                        .WithMany("ConsentLogs")
                        .HasForeignKey("KlientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Klienti");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.KlientProgram", b =>
                {
                    b.HasOne("WellnessAPI.Models.Domain.Klient", "Klienti")
                        .WithMany("KlientProgramet")
                        .HasForeignKey("KlientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WellnessAPI.Models.Domain.Program", "Programi")
                        .WithMany("KlientProgramet")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Klienti");

                    b.Navigation("Programi");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.ShitjeProdukteve", b =>
                {
                    b.HasOne("WellnessAPI.Models.Domain.Klient", "Klienti")
                        .WithMany("ShitjetProduktet")
                        .HasForeignKey("KlientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WellnessAPI.Models.Domain.Produkt", "Produkti")
                        .WithMany("Shitjet")
                        .HasForeignKey("ProduktId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Klienti");

                    b.Navigation("Produkti");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.Terapist", b =>
                {
                    b.HasOne("WellnessAPI.Models.Domain.Lokacioni", "Lokacioni")
                        .WithMany("Terapistet")
                        .HasForeignKey("LokacioniId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Lokacioni");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.Termin", b =>
                {
                    b.HasOne("WellnessAPI.Models.Domain.Klient", "Klienti")
                        .WithMany("Terminet")
                        .HasForeignKey("KlientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WellnessAPI.Models.Domain.Lokacioni", "Lokacioni")
                        .WithMany("Terminet")
                        .HasForeignKey("LokacioniId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WellnessAPI.Models.Domain.Sherbim", "Sherbimi")
                        .WithMany("Terminet")
                        .HasForeignKey("SherbimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WellnessAPI.Models.Domain.Terapist", "Terapisti")
                        .WithMany("Terminet")
                        .HasForeignKey("TerapistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Klienti");

                    b.Navigation("Lokacioni");

                    b.Navigation("Sherbimi");

                    b.Navigation("Terapisti");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.Vleresim", b =>
                {
                    b.HasOne("WellnessAPI.Models.Domain.Klient", "Klienti")
                        .WithMany("Vlereisimet")
                        .HasForeignKey("KlientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WellnessAPI.Models.Domain.Sherbim", "Sherbimi")
                        .WithMany("Vlereisimet")
                        .HasForeignKey("SherbimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WellnessAPI.Models.Domain.Terapist", "Terapisti")
                        .WithMany("Vlereisimet")
                        .HasForeignKey("TerapistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Klienti");

                    b.Navigation("Sherbimi");

                    b.Navigation("Terapisti");
                });

            modelBuilder.Entity("WellnessAPI.Models.Identity.PasswordResetToken", b =>
                {
                    b.HasOne("WellnessAPI.Models.Identity.ApplicationUser", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WellnessAPI.Models.Identity.RefreshToken", b =>
                {
                    b.HasOne("WellnessAPI.Models.Identity.ApplicationUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.Klient", b =>
                {
                    b.Navigation("Anetaresimet");

                    b.Navigation("ConsentLogs");

                    b.Navigation("KlientProgramet");

                    b.Navigation("ShitjetProduktet");

                    b.Navigation("Terminet");

                    b.Navigation("Vlereisimet");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.Lokacioni", b =>
                {
                    b.Navigation("Terapistet");

                    b.Navigation("Terminet");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.PaketaWellness", b =>
                {
                    b.Navigation("Anetaresimet");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.Produkt", b =>
                {
                    b.Navigation("Shitjet");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.Program", b =>
                {
                    b.Navigation("KlientProgramet");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.Sherbim", b =>
                {
                    b.Navigation("Terminet");

                    b.Navigation("Vlereisimet");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.Terapist", b =>
                {
                    b.Navigation("Terminet");

                    b.Navigation("Vlereisimet");
                });

            modelBuilder.Entity("WellnessAPI.Models.Identity.ApplicationUser", b =>
                {
                    b.Navigation("PasswordResetTokens");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
