// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WellnessAPI.Data;

#nullable disable

namespace WellnessAPI.MigrationsMySql
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260412221047_InitialMySql")]
    partial class InitialMySql
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.Anetaresim", b =>
                {
                    b.Property<int>("AnetaresimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AnetaresimId"));

                    b.Property<decimal>("CmimiPaguar")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("DataFillimit")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataMbarimit")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("KlientId")
                        .HasColumnType("int");

                    b.Property<int>("PaketId")
                        .HasColumnType("int");

                    b.Property<string>("Statusi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("AnetaresimId");

                    b.HasIndex("KlientId");

                    b.HasIndex("PaketId");

                    b.ToTable("Anetaresimet");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EntityId")
                        .HasColumnType("longtext");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("NewValues")
                        .HasColumnType("longtext");

                    b.Property<string>("OldValues")
                        .HasColumnType("longtext");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.Klient", b =>
                {
                    b.Property<int>("KlientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("KlientId"));

                    b.Property<DateTime?>("DataLindjes")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataRegjistrimit")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Emri")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FotoPath")
                        .HasColumnType("longtext");

                    b.Property<string>("Gjinia")
                        .HasColumnType("longtext");

                    b.Property<string>("KushtetShendetesore")
                        .HasColumnType("longtext");

                    b.Property<string>("Mbiemri")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefoni")
                        .HasColumnType("longtext");

                    b.HasKey("KlientId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Klientet");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.KlientProgram", b =>
                {
                    b.Property<int>("KpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("KpId"));

                    b.Property<DateTime>("DataFillimit")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataMbarimit")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("KlientId")
                        .HasColumnType("int");

                    b.Property<int>("ProgramId")
                        .HasColumnType("int");

                    b.Property<int>("Progresi")
                        .HasColumnType("int");

                    b.Property<string>("Statusi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("KpId");

                    b.HasIndex("KlientId");

                    b.HasIndex("ProgramId");

                    b.ToTable("KlientProgramet");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.PaketaWellness", b =>
                {
                    b.Property<int>("PaketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PaketId"));

                    b.Property<bool>("Aktive")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Cmimi")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("EmriPaketes")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("KohezgjatjaMuaj")
                        .HasColumnType("int");

                    b.Property<string>("Pershkrimi")
                        .HasColumnType("longtext");

                    b.Property<string>("SherbimiPerfshire")
                        .HasColumnType("longtext");

                    b.HasKey("PaketId");

                    b.ToTable("PaketaWellness");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.Produkt", b =>
                {
                    b.Property<int>("ProduktId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProduktId"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Cmimi")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("EmriProduktit")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Kategoria")
                        .HasColumnType("longtext");

                    b.Property<string>("Pershkrimi")
                        .HasColumnType("longtext");

                    b.Property<int>("SasiaStok")
                        .HasColumnType("int");

                    b.HasKey("ProduktId");

                    b.ToTable("Produktet");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.Program", b =>
                {
                    b.Property<int>("ProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProgramId"));

                    b.Property<string>("Dieta")
                        .HasColumnType("longtext");

                    b.Property<string>("EmriProgramit")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("KohezgjatjaJave")
                        .HasColumnType("int");

                    b.Property<string>("Pershkrimi")
                        .HasColumnType("longtext");

                    b.Property<string>("Qellimi")
                        .HasColumnType("longtext");

                    b.Property<string>("Ushtrimet")
                        .HasColumnType("longtext");

                    b.HasKey("ProgramId");

                    b.ToTable("Programet");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.Sherbim", b =>
                {
                    b.Property<int>("SherbimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SherbimId"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Cmimi")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("EmriSherbimit")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Kategoria")
                        .HasColumnType("longtext");

                    b.Property<int>("KohezgjatjaMin")
                        .HasColumnType("int");

                    b.Property<string>("Pershkrimi")
                        .HasColumnType("longtext");

                    b.HasKey("SherbimId");

                    b.ToTable("Sherbimet");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.ShitjeProdukteve", b =>
                {
                    b.Property<int>("ShitjeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ShitjeId"));

                    b.Property<decimal>("CmimiTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("DataShitjes")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("KlientId")
                        .HasColumnType("int");

                    b.Property<int>("ProduktId")
                        .HasColumnType("int");

                    b.Property<int>("Sasia")
                        .HasColumnType("int");

                    b.HasKey("ShitjeId");

                    b.HasIndex("KlientId");

                    b.HasIndex("ProduktId");

                    b.ToTable("ShitjetProduktet");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.Terapist", b =>
                {
                    b.Property<int>("TerapistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TerapistId"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Emri")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Licenca")
                        .HasColumnType("longtext");

                    b.Property<string>("Mbiemri")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Specializimi")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefoni")
                        .HasColumnType("longtext");

                    b.HasKey("TerapistId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Terapistet");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.Termin", b =>
                {
                    b.Property<int>("TerminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TerminId"));

                    b.Property<DateTime>("DataTerminit")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("KlientId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("OraFillimit")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("OraMbarimit")
                        .HasColumnType("time(6)");

                    b.Property<string>("Shenimet")
                        .HasColumnType("longtext");

                    b.Property<int>("SherbimId")
                        .HasColumnType("int");

                    b.Property<string>("Statusi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TerapistId")
                        .HasColumnType("int");

                    b.HasKey("TerminId");

                    b.HasIndex("KlientId");

                    b.HasIndex("SherbimId");

                    b.HasIndex("TerapistId");

                    b.ToTable("Terminet");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.Vleresim", b =>
                {
                    b.Property<int>("VleresimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("VleresimId"));

                    b.Property<DateTime>("DataVleresimit")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("KlientId")
                        .HasColumnType("int");

                    b.Property<string>("Komenti")
                        .HasColumnType("longtext");

                    b.Property<int>("Nota")
                        .HasColumnType("int");

                    b.Property<int>("SherbimId")
                        .HasColumnType("int");

                    b.Property<int>("TerapistId")
                        .HasColumnType("int");

                    b.HasKey("VleresimId");

                    b.HasIndex("KlientId");

                    b.HasIndex("SherbimId");

                    b.HasIndex("TerapistId");

                    b.ToTable("Vlereisimet");
                });

            modelBuilder.Entity("WellnessAPI.Models.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("KlientId")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("WellnessAPI.Models.Identity.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WellnessAPI.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WellnessAPI.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WellnessAPI.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WellnessAPI.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.Anetaresim", b =>
                {
                    b.HasOne("WellnessAPI.Models.Domain.Klient", "Klienti")
                        .WithMany("Anetaresimet")
                        .HasForeignKey("KlientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WellnessAPI.Models.Domain.PaketaWellness", "Paketa")
                        .WithMany("Anetaresimet")
                        .HasForeignKey("PaketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Klienti");

                    b.Navigation("Paketa");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.KlientProgram", b =>
                {
                    b.HasOne("WellnessAPI.Models.Domain.Klient", "Klienti")
                        .WithMany("KlientProgramet")
                        .HasForeignKey("KlientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WellnessAPI.Models.Domain.Program", "Programi")
                        .WithMany("KlientProgramet")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Klienti");

                    b.Navigation("Programi");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.ShitjeProdukteve", b =>
                {
                    b.HasOne("WellnessAPI.Models.Domain.Klient", "Klienti")
                        .WithMany("ShitjetProduktet")
                        .HasForeignKey("KlientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WellnessAPI.Models.Domain.Produkt", "Produkti")
                        .WithMany("Shitjet")
                        .HasForeignKey("ProduktId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Klienti");

                    b.Navigation("Produkti");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.Termin", b =>
                {
                    b.HasOne("WellnessAPI.Models.Domain.Klient", "Klienti")
                        .WithMany("Terminet")
                        .HasForeignKey("KlientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WellnessAPI.Models.Domain.Sherbim", "Sherbimi")
                        .WithMany("Terminet")
                        .HasForeignKey("SherbimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WellnessAPI.Models.Domain.Terapist", "Terapisti")
                        .WithMany("Terminet")
                        .HasForeignKey("TerapistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Klienti");

                    b.Navigation("Sherbimi");

                    b.Navigation("Terapisti");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.Vleresim", b =>
                {
                    b.HasOne("WellnessAPI.Models.Domain.Klient", "Klienti")
                        .WithMany("Vlereisimet")
                        .HasForeignKey("KlientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WellnessAPI.Models.Domain.Sherbim", "Sherbimi")
                        .WithMany("Vlereisimet")
                        .HasForeignKey("SherbimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WellnessAPI.Models.Domain.Terapist", "Terapisti")
                        .WithMany("Vlereisimet")
                        .HasForeignKey("TerapistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Klienti");

                    b.Navigation("Sherbimi");

                    b.Navigation("Terapisti");
                });

            modelBuilder.Entity("WellnessAPI.Models.Identity.RefreshToken", b =>
                {
                    b.HasOne("WellnessAPI.Models.Identity.ApplicationUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.Klient", b =>
                {
                    b.Navigation("Anetaresimet");

                    b.Navigation("KlientProgramet");

                    b.Navigation("ShitjetProduktet");

                    b.Navigation("Terminet");

                    b.Navigation("Vlereisimet");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.PaketaWellness", b =>
                {
                    b.Navigation("Anetaresimet");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.Produkt", b =>
                {
                    b.Navigation("Shitjet");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.Program", b =>
                {
                    b.Navigation("KlientProgramet");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.Sherbim", b =>
                {
                    b.Navigation("Terminet");

                    b.Navigation("Vlereisimet");
                });

            modelBuilder.Entity("WellnessAPI.Models.Domain.Terapist", b =>
                {
                    b.Navigation("Terminet");

                    b.Navigation("Vlereisimet");
                });

            modelBuilder.Entity("WellnessAPI.Models.Identity.ApplicationUser", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
